server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/attendance
  devtools:
    restart:
      enabled: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sa-token:
  token-name: token
  timeout: 2592000
  token-style: uuid
  is-log: true
  jwt-secret-key: fdsahohgfniojsvmcxzrt
logging:
  level:
    root: error
  file:
    name: log/dev_app.log