server:
  port: 8080
spring:
  redis:
    host: 175.178.116.245
    port: 8120
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://175.178.116.245:3306/attendance
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sa-token:
  token-name: cookie
  timeout: 2592000
  token-style: uuid
  is-log: true
logging:
  level:
    root: info
  file:
    name: log/dev_app.log
